- alias: "Garage - Arrival Notification"
  id: garage_arrival_notification_v2
  trigger:
    - platform: state
      entity_id: person.john_spencer
      to: "home"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: cover.ratgdo32disco_fd8d8c_door
          state: "closed"
        - condition: state
          entity_id: cover.ratgdo32disco_5735e8_door
          state: "closed"
  action:
    - service: notify.mobile_app_john_s_phone
      data:
        title: "🏠 Welcome Home"
        message: "Open garage door?"
        data:
          actions:
            - action: "OPEN_GARAGE_NORTH"
              title: "North"
            - action: "OPEN_GARAGE_SOUTH"
              title: "South"
            - action: "DISMISS_GARAGE"
              title: "Dismiss"
          ttl: 0
          priority: high
    - service: light.turn_on
      target:
        entity_id:
          - light.front_driveway
          - light.garage
      data:
        brightness_pct: 100
  mode: single

- alias: "Garage - Open Action Handler"
  id: garage_open_handler_v2
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "OPEN_GARAGE_NORTH"
      id: north
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "OPEN_GARAGE_SOUTH"
      id: south
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: north
          sequence:
            - service: cover.open_cover
              target:
                entity_id: cover.ratgdo32disco_fd8d8c_door
        - conditions:
            - condition: trigger
              id: south
          sequence:
            - service: cover.open_cover
              target:
                entity_id: cover.ratgdo32disco_5735e8_door
    - delay:
        seconds: 15
    - service: notify.mobile_app_john_s_phone
      data:
        title: "🚗 Garage Open"
        message: "Close door now?"
        data:
          actions:
            - action: "CLOSE_GARAGE_NORTH"
              title: "Close North"
            - action: "CLOSE_GARAGE_SOUTH"
              title: "Close South"
            - action: "LEAVE_OPEN"
              title: "Leave Open"
          ttl: 0
          priority: high
  mode: single

- alias: "Garage - Close Action Handler"
  id: garage_close_handler_v2
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "CLOSE_GARAGE_NORTH"
      id: north
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "CLOSE_GARAGE_SOUTH"
      id: south
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: north
          sequence:
            - service: cover.close_cover
              target:
                entity_id: cover.ratgdo32disco_fd8d8c_door
        - conditions:
            - condition: trigger
              id: south
          sequence:
            - service: cover.close_cover
              target:
                entity_id: cover.ratgdo32disco_5735e8_door
  mode: single
