# ============================================================================
# Aqara Sensor Friendly Names
# Created: 2026-01-25
# Maps generic sensor names to room locations
# ============================================================================

homeassistant:
  customize:
    # Sensor 1 - 1st Floor Bathroom
    sensor.aqara_temp_humidity_sensor_temperature:
      friendly_name: "1st Floor Bathroom Temperature"
    sensor.aqara_temp_humidity_sensor_humidity:
      friendly_name: "1st Floor Bathroom Humidity"

    # Sensor 2 - Basement
    sensor.aqara_temp_humidity_sensor_temperature_2:
      friendly_name: "Basement Temperature"
    sensor.aqara_temp_humidity_sensor_humidity_2:
      friendly_name: "Basement Humidity"

    # Sensor 3 - Upstairs Hallway
    sensor.aqara_temp_humidity_sensor_temperature_3:
      friendly_name: "Upstairs Hallway Temperature"
    sensor.aqara_temp_humidity_sensor_humidity_3:
      friendly_name: "Upstairs Hallway Humidity"

    # Sensor 4 - Upstairs Bathroom
    sensor.aqara_temp_humidity_sensor_temperature_4:
      friendly_name: "Upstairs Bathroom Temperature"
    sensor.aqara_temp_humidity_sensor_humidity_4:
      friendly_name: "Upstairs Bathroom Humidity"

    # Sensor 5 - Ella's Bedroom
    sensor.aqara_temp_humidity_sensor_temperature_5:
      friendly_name: "Ella's Bedroom Temperature"
    sensor.aqara_temp_humidity_sensor_humidity_5:
      friendly_name: "Ella's Bedroom Humidity"

    # Sensor 6 - Alaina's Bedroom
    sensor.aqara_temp_humidity_sensor_temperature_6:
      friendly_name: "Alaina's Bedroom Temperature"
    sensor.aqara_temp_humidity_sensor_humidity_6:
      friendly_name: "Alaina's Bedroom Humidity"

    # Sensor 7 - Garage
    sensor.aqara_temp_humidity_sensor_temperature_7:
      friendly_name: "Garage Aqara Temperature"
    sensor.aqara_temp_humidity_sensor_humidity_7:
      friendly_name: "Garage Aqara Humidity"
