# ===========================================================================
# UPSTAIRS LIGHTING PACKAGE
# Upstairs Hallway - Motion-activated
# SIMPLE: Energize (bright) on motion, OFF when clear. No dim modes.
# ===========================================================================

automation:
  - id: upstairs_hallway_motion_lighting_v2
    alias: "Upstairs Hallway → Motion Lighting v2"
    description: "Bright on motion, off when clear - no dim modes"
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.upstairs_bathroom_motion
        to: "on"
        id: motion_on
      - platform: state
        entity_id: binary_sensor.upstairs_bathroom_motion
        to: "off"
        for:
          minutes: 3
        id: motion_off
    action:
      - choose:
          # ── MOTION ON - ALWAYS BRIGHT ──
          - conditions:
              - condition: trigger
                id: motion_on
            sequence:
              - action: scene.turn_on
                target:
                  entity_id: scene.upstairs_hallway_energize
          # ── MOTION OFF - ALWAYS OFF ──
          - conditions:
              - condition: trigger
                id: motion_off
            sequence:
              - action: light.turn_off
                target:
                  entity_id: light.upstairs_hallway
                data:
                  transition: 2
